###
## Testing API Endpoints


########################
# Users Controller
########################


### Create New User
POST http://localhost:3000/api/v1/user
Content-Type: application/json

{
    "username": "le",
    "password": "cesarle",
    "email": "clee@gmail.com",  
    "name": "Tutte",
    "role": "user"
}

### Update User
PATCH http://localhost:3000/api/v1/user/1
Content-Type: application/json

{
    "username": "cle20",
    "password": "111111cesar"
}

### Delete User
DELETE http://localhost:3000/api/v1/user/31

########################
# Auth Controller
########################

### Login Test
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "cle20",
    "password": "password123"
}


### Logout Test
POST http://localhost:3000/api/v1/auth/logout

########################
# Users Controller
########################

### Seed Users
POST http://localhost:3000/api/v1/user/seed

### Get All Users
GET http://localhost:3000/api/v1/user


########################
# Activities Controller
########################


### Seed Activities
POST http://localhost:3000/api/v1/activity/seed
Content-Type: application/json

### Get All Activities
GET http://localhost:3000/api/v1/activity


### Create New Activity
POST http://localhost:3000/api/v1/activity
Content-Type: application/json

{
  "userId": 1,
  "type": "Running",
  "distance": 5.2,
  "duration": 45,
  "date": "2025-05-01T08:30:00Z",
  "location": "Central Park, New York"
}

### Update Activity
PATCH http://localhost:3000/api/v1/activity/7
Content-Type: application/json

{
    "userId": 1,
    "type": "Swim",
    "distance": 3.0,
    "duration": 45,
    "date": "2025-05-25",
    "location": {
        "lat": 41.7459793,
        "lng": -74.082801
    }
}

### Delete Activity
DELETE http://localhost:3000/api/v1/activity/6


########################
# Post Controller
########################
### Create Posts
POST http://localhost:3000/api/v1/posts
Content-Type: application/json

{
      "userId": 1,
      "username": "cle20",
      "type": "Running",
      "content": "Beautiful day!",
      "duration": 300,
      "distance": 3.1,
      "location": "New Paltz Trail"
}

### Get All Posts
GET http://localhost:3000/api/v1/posts
### Get Posts
GET http://localhost:3000/api/v1/posts/1

### Update Posts
PATCH http://localhost:3000/api/v1/posts/1
Content-Type: application/json
 {
      "userId": 1,
      "username": "cle20",
      "type": "Running",
      "content": "Afernoon run at the park. Beautiful day!",
      "duration": 30,
      "distance": 3.5,
      "location": "New Paltz Trail"

    }

### Delete Posts
DELETE http://localhost:3000/api/v1/posts/6
